# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  operating_system: ubuntu22

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  SECRET_KEY: "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"
  GPTAPI_KEY: "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"
  GOOGLE_CLIENT_ID: "255099809593-78h1jr7mubuto6s7iern9ebdf0l14umk.apps.googleusercontent.com"
  OAUTHLIB_INSECURE_TRANSPORT: "1"